# Generated by Django 5.2.12 on 2026-04-04 15:35

import django.db.models.deletion
import shopman.doorman.models.access_link
import shopman.doorman.models.device_trust
import shopman.doorman.models.verification_code
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.UUIDField(db_index=True, help_text='UUID do cliente no Customers', unique=True, verbose_name='ID do cliente')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Metadados do vínculo. Ex: {"device": "Chrome/120", "ip": "192.168.1.1"}', verbose_name='metadados')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doorman_customer_user', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'perfil de usuário',
                'verbose_name_plural': 'perfis de usuário',
                'db_table': 'doorman_customer_user',
            },
        ),
        migrations.CreateModel(
            name='TrustedDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer_id', models.UUIDField(db_index=True, help_text='UUID do cliente no Customers', verbose_name='ID do cliente')),
                ('token_hash', models.CharField(db_index=True, help_text='HMAC-SHA256 do token do cookie.', max_length=64, unique=True, verbose_name='hash do token')),
                ('user_agent', models.CharField(blank=True, default='', max_length=512, verbose_name='user agent')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='endereço IP')),
                ('label', models.CharField(blank=True, default='', help_text="Ex: 'Chrome no iPhone', derivado do user-agent.", max_length=100, verbose_name='rótulo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('expires_at', models.DateTimeField(default=shopman.doorman.models.device_trust._default_expires_at, verbose_name='expira em')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='último uso')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
            ],
            options={
                'verbose_name': 'dispositivo confiável',
                'verbose_name_plural': 'dispositivos confiáveis',
                'db_table': 'doorman_trusted_device',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['customer_id', 'is_active'], name='doorman_tru_custome_57d429_idx'), models.Index(fields=['expires_at'], name='doorman_tru_expires_1e2749_idx')],
            },
        ),
        migrations.CreateModel(
            name='VerificationCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code_hash', models.CharField(default=shopman.doorman.models.verification_code.generate_code, help_text='HMAC-SHA256 do código OTP. Nunca armazena plaintext.', max_length=64, verbose_name='hash do código')),
                ('target_value', models.CharField(db_index=True, help_text='Telefone em E.164 ou email.', max_length=255, verbose_name='valor destino')),
                ('purpose', models.CharField(choices=[('login', 'Login'), ('verify_contact', 'Verificar Contato')], default='login', max_length=20, verbose_name='finalidade')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('sent', 'Enviado'), ('verified', 'Verificado'), ('expired', 'Expirado'), ('failed', 'Falhou')], default='pending', max_length=20, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('expires_at', models.DateTimeField(default=shopman.doorman.models.verification_code.default_code_expiry, verbose_name='expira em')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='enviado em')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='verificado em')),
                ('delivery_method', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('sms', 'SMS'), ('email', 'Email')], default='whatsapp', max_length=20, verbose_name='método de envio')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='tentativas')),
                ('max_attempts', models.PositiveSmallIntegerField(default=shopman.doorman.models.verification_code._default_max_attempts, verbose_name='máximo de tentativas')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='endereço IP')),
                ('customer_id', models.UUIDField(blank=True, help_text='UUID do cliente no Customers', null=True, verbose_name='ID do cliente')),
            ],
            options={
                'verbose_name': 'código de verificação',
                'verbose_name_plural': 'códigos de verificação',
                'db_table': 'doorman_verification_code',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['target_value', 'status', 'created_at'], name='doorman_ver_target__b81d91_idx'), models.Index(fields=['expires_at'], name='doorman_ver_expires_48f0c9_idx')],
            },
        ),
        migrations.CreateModel(
            name='AccessLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(db_index=True, default=shopman.doorman.models.access_link.generate_token, max_length=64, unique=True, verbose_name='token')),
                ('customer_id', models.UUIDField(db_index=True, help_text='UUID do cliente no Customers', verbose_name='ID do cliente')),
                ('audience', models.CharField(choices=[('web_checkout', 'Checkout'), ('web_account', 'Conta'), ('web_support', 'Suporte'), ('web_general', 'Geral')], default='web_general', help_text='Escopo do token', max_length=20, verbose_name='audiência')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('expires_at', models.DateTimeField(default=shopman.doorman.models.access_link.default_expiry, verbose_name='expira em')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='usado em')),
                ('source', models.CharField(choices=[('manychat', 'ManyChat'), ('internal', 'Interno'), ('api', 'API')], default='manychat', max_length=20, verbose_name='origem')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Metadados do token. Ex: {"device": "iPhone 15", "login_source": "whatsapp"}', verbose_name='metadados')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doorman_access_links', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'link de acesso',
                'verbose_name_plural': 'links de acesso',
                'db_table': 'doorman_access_link',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['customer_id', 'created_at'], name='doorman_acc_custome_9e1f6b_idx'), models.Index(fields=['expires_at'], name='doorman_acc_expires_b47ec7_idx')],
            },
        ),
    ]
